# Generated by Django 5.0.8 on 2024-09-02 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "статья", "verbose_name_plural": "статьи"},
        ),
    ]
